# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
            distribution: 'adopt' # See 'Supported distributions' for available options
            java-version: '8'
            java-package: jdk
    # Install Ant and gpg and curl
    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant gnupg2 curl
    - run: ant -noinput -buildfile build.xml dist test
